### ISSUE TITLE
Unable to load object

### ISSUE THREAD

**Issue by ghost** [Sachinbhola/DecoratAR-Android-app#2]
hi ~ @Sachinbhola  

I am trying to clone your project and run it to study android ar.
When I click on the current object, it says there is a problem, can you tell me the cause?

D/InputMethodManager: getNavigationBarColor() -855310
I/mali_egl: eglDestroySurface() in
I/mali_winsys: delete_surface() [1080x2220] return
I/mali_egl: eglDestroySurface() out
W/libEGL: EGLNativeWindowType 0x7f138a9f10 disconnect failed
I/ViewRootImpl@dcaf963[MainActivity2]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)8 dur=7 res=0x5 s={false 0} ch=true
I/ViewRootImpl@dcaf963[MainActivity2]: stopped(true) old=false
I/ViewRootImpl@dcaf963[MainActivity2]: Relayout returned: old=(0,0,1080,2220) new=(0,0,1080,2220) req=(1080,2220)8 dur=8 res=0x5 s={false 0} ch=false

**Comment by Sachinbhola** [comment]
Hi,

I would be glad to help, just send me a screenshot of error message that
you have received
